//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int UrunId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string UrunAd { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public Nullable<short> UrunAdet { get; set; }
    }
}
